/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#51606b",
        "primary": "#202f38",
        "outline": "#73777b",
        "tertiary-fixed": "#e3e2e2",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#e9c349",
        "surface-container-high": "#e9e8e5",
        "on-tertiary-fixed-variant": "#464747",
        "on-surface-variant": "#43474b",
        "on-primary-fixed": "#0e1d26",
        "on-secondary-fixed-variant": "#574500",
        "surface-container-highest": "#e3e2e0",
        "tertiary-container": "#424343",
        "surface-dim": "#dbdad7",
        "secondary": "#735c00",
        "secondary-accent": "#d4af37",
        "on-tertiary-container": "#afb0b0",
        "surface": "#faf9f6",
        "surface-variant": "#e3e2e0",
        "error-container": "#ffdad6",
        "background": "#faf9f6",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#3a4953",
        "primary-container": "#36454f",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d5e5f1",
        "inverse-primary": "#b9c9d5",
        "on-tertiary-fixed": "#1a1c1c",
        "on-secondary-fixed": "#241a00",
        "secondary-container": "#fed65b",
        "inverse-on-surface": "#f2f1ee",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#a2b2be",
        "on-primary": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "outline-variant": "#c3c7cb",
        "on-error-container": "#93000a",
        "on-secondary-container": "#745c00",
        "secondary-fixed": "#ffe088",
        "tertiary": "#2b2d2d",
        "surface-container": "#efeeeb",
        "surface-bright": "#faf9f6",
        "tertiary-fixed-dim": "#c6c6c6",
        "inverse-surface": "#2f312f",
        "on-surface": "#1a1c1a",
        "primary-fixed-dim": "#b9c9d5",
        "on-error": "#ffffff",
        "on-background": "#1a1c1a"
      },
      spacing: {
        "edge-margin-mobile": "24px",
        "stack-md": "16px",
        "section-gap": "120px",
        "container-max": "1440px",
        "stack-lg": "32px",
        "edge-margin-desktop": "80px",
        "stack-sm": "8px",
        "gutter": "32px"
      },
      fontFamily: {
        "headline": ["'Libre Caslon Text'", "serif"],
        "body": ["'Manrope'", "sans-serif"],
        "headline-lg-mobile": ["'Libre Caslon Text'", "serif"],
        "body-lg": ["'Manrope'", "sans-serif"],
        "headline-lg": ["'Libre Caslon Text'", "serif"],
        "body-md": ["'Manrope'", "sans-serif"],
        "headline-md": ["'Libre Caslon Text'", "serif"],
        "display-lg": ["'Libre Caslon Text'", "serif"],
        "label-caps": ["'Manrope'", "sans-serif"]
      }
    },
  },
  plugins: [],
}
